import React, { Component } from 'react';

import ImgAd1 from './img/7.png';
import ImgAdLogo1 from './img/9.png';
import codeImg1 from './img/10.png';
import moreInfoImg1 from './img/7.png';
import moreInfoImg2 from './img/12.png';


export const ortOptions =[
    {key:'0', value:'0', text:'Alles'},
    {key:'1', value:'1', text:'ort 1'},
    {key:'2', value:'2', text:'ort 2'},
    {key:'3', value:'3', text:'ort 3'},
    {key:'4', value:'4', text:'ort 4'},
    {key:'5', value:'5', text:'ort 5'},
    {key:'6', value:'6', text:'ort 6'},

]

export const bewOptions =[
    {key:'0', value:'0', text:'Alles'},
    {key:'1', value:'1', text:'1 sterne'},
    {key:'2', value:'2', text:'2 sterne'},
    {key:'3', value:'3', text:'3 sterne'},
    {key:'4', value:'4', text:'4 sterne'},
    {key:'5', value:'5', text:'5 sterne'},
]



export let segmentAds = [
    {
        name:'VIVACOLOR 1',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 1',
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '1',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 2',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 2',
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '2',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0,
    },
    {
        name:'VIVACOLOR 3',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 3',
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '3',
        five:27,
        four: 15,
        three: 4,
        two: 0,
        one: 0,
    },
    {
        name:'VIVACOLOR 4',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 3',
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '4',
        five:7,
        four: 25,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 5',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 2',
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '5',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 6',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 5',
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '6',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 7',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 4',
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '7',
        five:17,
        four: 15,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 8',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 5',
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '8',
        five:11,
        four: 15,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 9',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 3',
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '9',
        five:11,
        four: 5,
        three: 14,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 10',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 1',
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '10',
        five:11,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 11',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 2',
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '11',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 12',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 6',
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '12',
        five:11,
        four: 170,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 13',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 6',
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '13',
        five:100,
        four: 50,
        three: 40,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 14',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 4',
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '14',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 15',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 3',
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '15',
        five:17,
        four: 115,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 16', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 6',
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '16',
        five:7,
        four: 5,
        three: 14,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 17', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 4',
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '1',
        five:117,
        four: 5,
        three: 4,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 17', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 1',
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '2',
        five:7,
        four: 5,
        three: 100,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 18', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 5',
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '3',
        five:117,
        four: 150,
        three: 40,
        two: 0,
        one: 0
    },
    {
        name:'VIVACOLOR 19', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1,
        ort:'ort 2',
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '4',
        five:7,
        four: 15,
        three: 4,
        two: 0,
        one: 0
    },
]

export const source = [
    {
        "title": "Administration / Sachbearbeitung",
        "price": segmentAds.filter(el=>el.grupation === '1').length,
        "grupation": "1"
    },
    {
        "title": "Bildung / Training / Erziehung ",
        "price": segmentAds.filter(el=>el.grupation === '2').length,
        "grupation": "2"
    },
    {
        "title": "Consulting",
        "price": segmentAds.filter(el=>el.grupation === '3').length,
        "grupation": "3"
    },
    {
        "title": "Einkauf / Logistik / Transport",
        "price": segmentAds.filter(el=>el.grupation === '4').length,
        "grupation": "4"
    },
    {
        "title": "Finanzwesen / Controlling ",
        "price": segmentAds.filter(el=>el.grupation === '5').length,
        "grupation": "5"
    },
    {
        "title": "Gastronomie / Hotel / Tourismus",
        "price": segmentAds.filter(el=>el.grupation === '6').length,
        "grupation": "6"
    },
    {
        "title": "Handwerk / Produktion ",
        "price": segmentAds.filter(el=>el.grupation === '7').length,
        "grupation": "7"
    },
    {
        "title": "IT / Telekommunikation ",
        "price": segmentAds.filter(el=>el.grupation === '8').length,
        "grupation": "8"
    },
    {
        "title": "Instandhaltung / Facility Management ",
        "price": segmentAds.filter(el=>el.grupation === '9').length,
        "grupation": "9"
    },
    {
        "title": "Landwirtschaft / Forstwirtschaft / Umwelt ",
        "price": segmentAds.filter(el=>el.grupation === '10').length,
        "grupation": "10"
    },
    {
        "title": "Marketing/PR",
        "price": segmentAds.filter(el=>el.grupation === '11').length,
        "grupation": "11"
    },
    {
        "title": "Medien / Verlagswesen / Kultur",
        "price": segmentAds.filter(el=>el.grupation === '12').length,
        "grupation": "12"
    },
    {
        "title": "Personalwesen ",
        "price": segmentAds.filter(el=>el.grupation === '13').length,
        "grupation": "13"
    },
    {
        "title": "Rechtswesen ",
        "price": segmentAds.filter(el=>el.grupation === '14').length,
        "grupation": "14"
    },
    {
        "title": "Technik / Ingenieurwesen ",
        "price": segmentAds.filter(el=>el.grupation === '15').length,
        "grupation": "15"
    },
    {
        "title":"Vertrieb / Handel ",
        "price": segmentAds.filter(el=>el.grupation === '16').length,
        "grupation": "16"
    }

]