import React, { Component } from 'react';

// import ImgAd1 from './img/7.png';
// import ImgAdLogo1 from './img/9.png';
// import codeImg1 from './img/10.png';
// import moreInfoImg1 from './img/7.png';
// import moreInfoImg2 from './img/12.png';

const ImgAd1 = 'http://hawd-design.net/rijad/wendoos-2/images/7.png';
const ImgAdLogo1 = 'http://hawd-design.net/rijad/wendoos-2/images/9.png';
const codeImg1 = 'http://hawd-design.net/rijad/wendoos-2/images/10.png';
const moreInfoImg1 = 'http://hawd-design.net/rijad/wendoos-2/images/7.png';
const moreInfoImg2 = 'http://hawd-design.net/rijad/wendoos-2/images/12.png';




export const ortOptions =[
    {key:'0', value:'0', text:'Alles'},
    {key:'1', value:'1', text:'Wien'},
    {key:'2', value:'2', text:'Burgenland'},
    {key:'3', value:'3', text:'Kärnten'},
    {key:'4', value:'4', text:'Nieder­österreich'},
    {key:'5', value:'5', text:'Ober­österreich'},
    {key:'6', value:'6', text:'Steiermark'},
    {key:'7', value:'7', text:'Salzburg'},
    {key:'8', value:'8', text:'Tirol'},
    {key:'9', value:'9', text:'Vorarlberg'},
]

export const bewOptions =[
    {key:'0', value:'0', text:'Alles'},
    {key:'1', value:'1', text:'1 sterne'},
    {key:'2', value:'2', text:'2 sterne'},
    {key:'3', value:'3', text:'3 sterne'},
    {key:'4', value:'4', text:'4 sterne'},
    {key:'5', value:'5', text:'5 sterne'},
]



export let segmentAds = [
    {
        title:'VIVACOLOR 1',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '1',
    },
    {
        title:'VIVACOLOR 2',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '2',
    },
    {
        title:'VIVACOLOR 3',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '3',
    },
    {
        title:'VIVACOLOR 4',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '4',
    },
    {
        title:'VIVACOLOR 5',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '5',
    },
    {
        title:'VIVACOLOR 6',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '6',
    },
    {
        title:'VIVACOLOR 7',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '7',
    },
    {
        title:'VIVACOLOR 8',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '8',
    },
    {
        title:'VIVACOLOR 9',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '9',
    },
    {
        title:'VIVACOLOR 10',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '10',
    },
    {
        title:'VIVACOLOR 11',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '11',
    },
    {
        title:'VIVACOLOR 12',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '12',
    },
    {
        title:'VIVACOLOR 13',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '13',
    },
    {
        title:'VIVACOLOR 14',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '14',
    },
    {
        title:'VIVACOLOR 15',
        imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'3',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '15',
    },
    {
        title:'VIVACOLOR 16', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'6',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '16',
    },
    {
        title:'VIVACOLOR 17', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'4',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '1',
    },
    {
        title:'VIVACOLOR 18', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'1',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '2',
    },
    {
        title:'VIVACOLOR 19', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'5',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '3',
    },
    {
        title:'VIVACOLOR 20', imgName:ImgAd1,
        imgLogoName:ImgAdLogo1, image:ImgAdLogo1,
        ortId:'2',
        address:'Margaretenstr. 109',
        phone:'+43 1 5442045',
        mail:'office@vivacolor.at',
        web:'vivacolor.at',
        descriptionText:'VIVACOLOR Farben & Autolacke ist ein Fachgeschäft für Farben, Putze, Lacke und Malerbedarf.',
        codeImg:codeImg1,
        moreInfoText:'Als Farbspezialist bieten wir Ihnen – ganz egal ob Profi oder Heimwerker – ein umfangreiches Sortiment für den Innen- und Außenbereich. Wir beraten Sie professionell und bieten Ihnen hochwertige Produkte zu fairen Preisen.',
        moreInfoImg1:moreInfoImg1,
        moreInfoImg2:moreInfoImg2,
        grupation: '4',
    },
]

export const sidebarGrupations = [
    {
        title: "Administration / Sachbearbeitung",
        count: segmentAds.filter(el=>el.grupation === '1').length,
        grupation: "1"
    },
    {
        title: "Bildung / Training / Erziehung ",
        count: segmentAds.filter(el=>el.grupation === '2').length,
        grupation: "2"
    },
    {
        title: "Consulting",
        count: segmentAds.filter(el=>el.grupation === '3').length,
        grupation: "3"
    },
    {
        title: "Einkauf / Logistik / Transport",
        count: segmentAds.filter(el=>el.grupation === '4').length,
        grupation: "4"
    },
    {
        title: "Finanzwesen / Controlling ",
        count: segmentAds.filter(el=>el.grupation === '5').length,
        grupation: "5"
    },
    {
        title: "Gastronomie / Hotel / Tourismus",
        count: segmentAds.filter(el=>el.grupation === '6').length,
        grupation: "6"
    },
    {
        title: "Handwerk / Produktion ",
        count: segmentAds.filter(el=>el.grupation === '7').length,
        grupation: "7"
    },
    {
        title: "IT / Telekommunikation ",
        count: segmentAds.filter(el=>el.grupation === '8').length,
        grupation: "8"
    },
    {
        title: "Instandhaltung / Facility Management ",
        count: segmentAds.filter(el=>el.grupation === '9').length,
        grupation: "9"
    },
    {
        title: "Landwirtschaft / Forstwirtschaft / Umwelt ",
        count: segmentAds.filter(el=>el.grupation === '10').length,
        grupation: "10"
    },
    {
        title: "Marketing/PR",
        count: segmentAds.filter(el=>el.grupation === '11').length,
        grupation: "11"
    },
    {
        title: "Medien / Verlagswesen / Kultur",
        count: segmentAds.filter(el=>el.grupation === '12').length,
        grupation: "12"
    },
    {
        title: "Personalwesen ",
        count: segmentAds.filter(el=>el.grupation === '13').length,
        grupation: "13"
    },
    {
        title: "Rechtswesen ",
        count: segmentAds.filter(el=>el.grupation === '14').length,
        grupation: "14"
    },
    {
        title: "Technik / Ingenieurwesen ",
        count: segmentAds.filter(el=>el.grupation === '15').length,
        grupation: "15"
    },
    {
        title:"Vertrieb / Handel ",
        count: segmentAds.filter(el=>el.grupation === '16').length,
        grupation: "16"
    }

]
